### ISSUE TITLE
Graphics and input is off

### ISSUE THREAD

**Issue by NanzeRT** [andstatus/game2048#10]
![Screenshot_20220429-105241_2048 Open Fun Game.jpg](https://user-images.githubusercontent.com/56739205/165905701-c6e9bfa1-d530-4abe-adc5-54fafbfa2073.jpg)

Field (blue) recives input in offseted place (red). Same thing for all input.

Android 11
Model: Galaxy Tab A
Game ver. 1.12.0
Screen diagonal: 10"

**Comment by yvolk** [comment]
Hi @NanzeRT 
Some time ago I investigated similar problem in one of devices. After a lot of time and tests it appeared that rotation to 180 degrees solved the problem. We couldn't believe this...
So please try all 4 possible orientations (4, not 2 only!) and post here, if there are any differences.

**Comment by NanzeRT** [comment]
Hi @yvolk 
It work the same in all 4 orientations. It seems like input scales the same amount with focus in top-left corner.

**Comment by NanzeRT** [comment]
It scales in about 75-80%

**Comment by yvolk** [comment]
@NanzeRT We didn't find a cause of the problem, but recently I upgraded the 2048 Game to the latest version of the graphics library (KorGe) + newer Kotlin version. Please check 2048 game v.1.13.1 here: #1
