### ISSUE TITLE
Issue with redoing a move and Non-random placement of tiles

### ISSUE THREAD

**Issue by pbarney** [andstatus/game2048#12]
I've noticed that when redoing a move, the newly placed number tile regenerates in the same exactly place about 90% of the time. So if you want to redo a move, you have to redo it at least twice.

Also, when redoing a move, the game doesn't seem to place the tiles in a completely random way. It tends to favor certain places in a statistically significant way.

**Comment by pbarney** [comment]
For clarification, I mean the _first_ time you redo a move, the new number is in the same place about 90% of the time. After the second undo it tends to move around, but seems to show favoritism for certain locations.

**Comment by yvolk** [comment]
@pbarney I quickly played to fill most of places and then tried to undo and redo. And I repeated this several times.
I didn't notice that some places are preferable...
![2048-undo](https://user-images.githubusercontent.com/207716/174141781-1a06f7c0-fbeb-4f91-bbeb-6e812b40bd90.png)
