### ISSUE TITLE
Text don't render properly.

### ISSUE THREAD

**Issue by SagXD** [andstatus/game2048#13]
Issue - Text doesn't render properly after clicking on sharing button.
Here is a video for better explanation.

https://github.com/andstatus/game2048/assets/95903022/a74bf981-6200-4a87-b541-00ca390570bd

Game Version 1.13.2
Using a Tab.

**Comment by yvolk** [comment]
@SagXD  I see, another regression after recent upgrades. Will fix.
These issues appeared after my recent upgrade of the graphic game engine. Thank you for reporting.

**Comment by yvolk** [comment]
Fixed in v.1.14.1, published at #1
