### ISSUE TITLE
Auto Rotation

### ISSUE THREAD

**Issue by SagXD** [andstatus/game2048#14]
After Rotating my tablet, app change it's orientation but didn't adjust the resolution.
![Screenshot_20230820-144209](https://github.com/andstatus/game2048/assets/95903022/4bbeafcb-3503-4c42-8112-e947a8eca25c)
![Screenshot_20230820-144221](https://github.com/andstatus/game2048/assets/95903022/6f0d067a-ec26-410d-b6bd-c8472e6f8d89)
 What I want is turn off the Auto Rotation in app or make it able change the resolution.
 
 Note - I was not using system auto rotation.

**Comment by yvolk** [comment]
Thanks @SagXD . I also noticed this (regression) problem in the latest version. Wil fix.

**Comment by yvolk** [comment]
Fixed in v.1.14.1, please see it at #1
