### ISSUE TITLE
Volume keys disabled

### ISSUE THREAD

**Issue by Roy-Orbison** [andstatus/game2048#15]
When this app is in the foreground, the volume buttons are turned into no-ops. This means I can't control music volume in the background, nor video volume of a popup. I have to tap the task switch button first to de-focus the game, without accidentally switching to another app, then adjust volume, then refocus it.

Is this intentional? Are the volume buttons meant to do something in-game?

**Comment by yvolk** [comment]
Hi @Roy-Orbison I tested it on my Android 13 device and volume keys work: I could change YouTube Music volume in the background.
What Android version does your device have?

**Comment by Roy-Orbison** [comment]
Sorry, forgot about this. It was 12, but I upgraded since.
