### ISSUE TITLE
 Issue with Delete Button Functionality and Menu Visibility

### ISSUE THREAD

**Issue by shamma13** [andstatus/game2048#22]
I encountered an issue while using the delete button in the game. Upon multiple attempts to use the delete button, I noticed inconsistent behavior where the game was not properly deleted, causing it to not properly restart. Additionally, when this issue occurs, the delete button disappears from the menu options when accessed.

How to reproduce:

1. Open the 2048 game app.
2. Swipe a few tiles.
3. Click the "Delete" button in the menu to delete the current game.
4. Repeat steps 2 and 3 multiple times.

behaviour:

https://github.com/andstatus/game2048/assets/95432232/b1e6ce2a-265a-48ae-bb85-554045b04054

**Comment by yvolk** [comment]
Hello @shamma13 
When you "Delete" current game, the app shows you some previously stored game. You can see all stored games in the "Recent games" menu item.
When you repeat your scenario, you delete another previous game.
And so on.
At some point there are too few "Recent games" left (as I remember, less than 5 games), and the app doesn't show you "Delete" button.

If you want to restart a game, just press "Try again" button.
