### ISSUE TITLE
Increase playing field

### ISSUE THREAD

**Issue by Fehertukor** [andstatus/game2048#9]
Thank you for your work!

Would it be possible to increase playing field size from
4x4
To
5x5
6x6
7x7
8x8
?

**Comment by yvolk** [comment]
@Fehertukor Thank you for the suggestion. Actually, I wrote the code having this option in mind, so this should be possible without app rewrite, I hope :-)

**Comment by yvolk** [comment]
Will look at this this weekend...

**Comment by yvolk** [comment]
@xIUPITERx @Fehertukor Please try v.1.13.0 Beta: I added "Select board size" menu item allowing to select boards from 3x3 to 8x8
Published here: #1 
![image](https://github.com/andstatus/game2048/assets/207716/0a911719-758f-4e2c-8eb3-7676b60f80d4)

**Comment by Fehertukor** [comment]
@yvolk @xIUPITERx It works like charm! Thank you for it!
